// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmwJUdCOmeSufwNwKziwAxi9evNOPug_M',
    appId: '1:554356368429:web:4655d42d6c8802cc72c4a4',
    messagingSenderId: '554356368429',
    projectId: 'presupuestos-6a894',
    authDomain: 'presupuestos-6a894.firebaseapp.com',
    storageBucket: 'presupuestos-6a894.firebasestorage.app',
    measurementId: 'G-MY2GQE2L48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5idKWaNeu57PCXUjYe24p6lV5siuPyhg',
    appId: '1:554356368429:android:9fe4907173ab64e272c4a4',
    messagingSenderId: '554356368429',
    projectId: 'presupuestos-6a894',
    storageBucket: 'presupuestos-6a894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2dK7wD7r8hI3gxehyFSNl9FVQU-QJQg',
    appId: '1:554356368429:ios:c0b56807cdb8256172c4a4',
    messagingSenderId: '554356368429',
    projectId: 'presupuestos-6a894',
    storageBucket: 'presupuestos-6a894.firebasestorage.app',
    iosBundleId: 'com.example.appPresupuesto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI2dK7wD7r8hI3gxehyFSNl9FVQU-QJQg',
    appId: '1:554356368429:ios:c0b56807cdb8256172c4a4',
    messagingSenderId: '554356368429',
    projectId: 'presupuestos-6a894',
    storageBucket: 'presupuestos-6a894.firebasestorage.app',
    iosBundleId: 'com.example.appPresupuesto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmwJUdCOmeSufwNwKziwAxi9evNOPug_M',
    appId: '1:554356368429:web:bfac2e7fb4cf73bc72c4a4',
    messagingSenderId: '554356368429',
    projectId: 'presupuestos-6a894',
    authDomain: 'presupuestos-6a894.firebaseapp.com',
    storageBucket: 'presupuestos-6a894.firebasestorage.app',
    measurementId: 'G-5E9Y2S1WZY',
  );
}
